posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('list', views.PostsListView.as_view(), name='list'),
    path('subscriber', views.addSubscriber, name='add-subscriber'),
]

wizardsite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
import datetime

from django.db import models
from django.utils import timezone

class Video(models.Model):
    title = models.CharField(max_length=100)
    short_description = models.CharField(max_length=250, blank=True, default='')
    full_description = models.TextField(blank=True, default='')
    video_id = models.CharField('Youtube video id', max_length=50, default='')
    dummy_image = models.ImageField(upload_to='uploads/videos/images/', default='')
    published_at = models.DateTimeField('date published', default=timezone.now)
    created_at = models.DateTimeField('date created', auto_now_add=True)
    updated_at = models.DateTimeField('date updated', auto_now=True)

    def __str__(self):
        return self.title
    
    def was_published_recently(self):
        return self.published_at >= timezone.now() - datetime.timedelta(days=5)
    
    was_published_recently.boolean = True


class Subscriber(models.Model):
    email = models.EmailField(max_length=254)
    supscribed_at = models.DateTimeField('date supscribed', auto_now_add=True)
    is_active = models.BooleanField('is active subscriber', default=True)

posts/views.py
from django.http import JsonResponse
from django.core.validators import validate_email
from django.http import Http404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.core.mail import send_mail

from .models import Video, Subscriber


class IndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_video_list'

    def get_queryset(self):
        return Video.objects.order_by('-published_at')[:6]

class PostsListView(generic.ListView):
    template_name = 'posts/posts-list.html'
    context_object_name = 'latest_video_list'
    # TODO:have to add pagination
    def get_queryset(self):
        return Video.objects.order_by('-published_at')


def addSubscriber(request):
    if request.method == 'POST':
        email = request.POST.get('email', '')
        terms = request.POST.get('terms', False)

        try:
            validate_email(email)

            # add new subscriber
            subscriber = Subscriber()
            subscriber.email = email
            subscriber.save()

            return JsonResponse({'error':False}, safe=False)

        except validate_email.ValidationError:
            return JsonResponse({'error':True, 'msg':'Invalid email address'}, safe=False)

    else:
        raise Http404


def sendSubscribeMail(email):
    send_mail(
        'Subject here',
        'Here is the message.',
        'from@example.com',
        [ email ],
        fail_silently=False,
    )

posts/templates/posts/posts-list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129038500-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-129038500-2');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Website Title -->
    <title>Wizard | Posts</title>

    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700,700i&amp;subset=latin-ext"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
    <link href="{% static 'posts/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'posts/css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'posts/css/swiper.css' %}" rel="stylesheet">
    <link href="{% static 'posts/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'posts/css/custom-styles.css' %}" rel="stylesheet">

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'posts/images/favicon-32x32.png' %}">
</head>

<body data-spy="scroll" data-target=".fixed-top">

    <!-- Preloader -->
    <div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->

    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top top-nav-collapse">
        <div class="container">

            <!-- Text Logo - Use this if you don't have a graphic logo -->
            <li><a class="navbar-brand logo-text mobile-only page-scroll" href="/">Wizard</a></li>

            <!-- Image Logo -->
            {% comment %}
            <a class="navbar-brand logo-image mobile-only page-scroll" href="index.html"><img
                    src="{% static 'posts/images/apple-icon-76x76.png'%}" alt="alternative"></a>
            {% endcomment %}

            <!-- Mobile Menu Toggle Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-awesome fas fa-bars"></span>
                <span class="navbar-toggler-awesome fas fa-times"></span>
            </button>
            <!-- end of mobile menu toggle button -->

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto mr-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="/">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll active" href="#">VIDEOS</a>
                    </li>

                    <!-- Text Logo - Use this if you don't have a graphic logo -->
                    <a class="navbar-brand logo-text larger-devices page-scroll" href="/">Wizard</a>

                    <!-- Image Logo -->
                    {% comment %} <li><a class="navbar-brand logo-image larger-devices page-scroll" href="#"><img
                                src="{% static 'posts/images/apple-icon-76x76.png'%}" alt="alternative"></a></li>
                    {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="/#about">ABOUT</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="/#extras">CONTACT</a>
                    </li>

                </ul>
            </div>
        </div> <!-- end of container -->
    </nav> <!-- end of navbar -->
    <!-- end of navigation -->

    <!-- Latest Videos -->
    <!-- Note: video lightbox works with youtube and vimeo links -->
    <div class="cards-1">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Latest Videos</h2>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
            <div class="row">
                <div class="col-lg-12">

                    {% for video in latest_video_list %}
                    <!-- Card -->
                    <div class="card">
                        <a class="popup-youtube" href="https://www.youtube.com/watch?v={{ video.video_id }}"
                            data-effect="fadeIn">
                            <img class="img-fluid" src="{{ MEDIA_URL }}{{ video.dummy_image }}" alt="alternative"></a>
                        <div class="card-body">
                            <h5 class="card-title">{{ video.title }}</h5>
                            <p>{{ video.short_description | safe | linebreaks }}</p>
                        </div>
                    </div>
                    <!-- end of card -->
                    {% endfor %}                     

                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of cards-1 -->
    <!-- end of latest videos -->

    <!-- Footer -->
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h4>For More Follow Us On</h4>
                    <span class="fa-stack fa-lg">
                        <a href="https://www.facebook.com/live.wizardlk/" target="_blank">
                            <i class="fas fa-circle fa-stack-2x facebook"></i>
                            <i class="fab fa-facebook-f fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack fa-lg">
                        <a href="https://twitter.com/Wizard_LK" target="_blank">
                            <i class="fas fa-circle fa-stack-2x twitter"></i>
                            <i class="fab fa-twitter fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack fa-lg">
                        <a href="https://www.instagram.com/wizard_lk/" target="_blank">
                            <i class="fas fa-circle fa-stack-2x instagram"></i>
                            <i class="fab fa-instagram fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack fa-lg">
                        <a href="https://www.youtube.com/channel/UC4MDglKGvqZwvKkvzzZ6eOQ" target="_blank">
                            <i class="fas fa-circle fa-stack-2x youtube"></i>
                            <i class="fab fa-youtube fa-stack-1x"></i>
                        </a>
                    </span>
                    <span class="fa-stack fa-lg">
                        <a href="https://github.com/wizardlk" target="_blank">
                            <i class="fas fa-circle fa-stack-2x github"></i>
                            <i class="fab fa-github fa-stack-1x"></i>
                        </a>
                    </span>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of footer -->
    <!-- end of footer -->


    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="p-small">Copyright © Xchord Software</a></p>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright -->
    <!-- end of copyright -->

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"
        integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
    <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'posts/js/popper.min.js'%}"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'posts/js/bootstrap.min.js'%}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'posts/js/jquery.easing.min.js'%}"></script>
    <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'posts/js/swiper.min.js'%}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'posts/js/jquery.magnific-popup.js'%}"></script> <!-- Magnific Popup for lightboxes -->
    <script src="{% static 'posts/js/morphext.min.js'%}"></script> <!-- Morphtext rotating text in the header-->
    <script src="{% static 'posts/js/validator.min.js'%}"></script>
    <!-- Validator.js - Bootstrap plugin that validates forms -->
    <script>
        var csrftoken = '{{ csrf_token }}';
        var add_subscriber_url = '{% url "posts:add-subscriber" %}';
    </script>
    <script src="{% static 'posts/js/posts/scripts.js'%}"></script> <!-- Custom scripts -->
</body>

</html>